/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jboss.rusheye.manager.gui.frames;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jboss.rusheye.manager.Main;
import org.jboss.rusheye.manager.gui.view.mask.MaskCase;
import org.jboss.rusheye.manager.gui.view.mask.converters.MaskConverter;
import org.jboss.rusheye.manager.gui.view.mask.converters.MaskToImageConverter;
import org.jboss.rusheye.manager.utils.FileChooserUtils;
import org.jboss.rusheye.suite.HorizontalAlign;
import org.jboss.rusheye.suite.Mask;
import org.jboss.rusheye.suite.MaskType;
import org.jboss.rusheye.suite.VerticalAlign;

/**
 *
 * @author hcube
 */
public class MaskAdder extends javax.swing.JFrame {

    private MaskCase node;

    /**
     * Creates new form MaskAdder
     */
    public MaskAdder(MaskCase mc) {
        node = mc;
        initComponents();
        nameTextField.setText(node.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        alphaRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        topRadioButton = new javax.swing.JRadioButton();
        bottomRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        leftRadioButton = new javax.swing.JRadioButton();
        rightRadioButton = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(alphaRadioButton);
        alphaRadioButton.setSelected(true);
        alphaRadioButton.setText("Selective alpha");

        jLabel1.setText("Mask type :");

        jLabel2.setText("Vertical align. :");

        buttonGroup2.add(topRadioButton);
        topRadioButton.setSelected(true);
        topRadioButton.setText("Top");

        buttonGroup2.add(bottomRadioButton);
        bottomRadioButton.setText("Bottom");

        jLabel3.setText("Horizontal align. :");

        buttonGroup3.add(leftRadioButton);
        leftRadioButton.setSelected(true);
        leftRadioButton.setText("Left");

        buttonGroup3.add(rightRadioButton);
        rightRadioButton.setText("Right");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alphaRadioButton)
                                    .addComponent(topRadioButton)
                                    .addComponent(bottomRadioButton))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leftRadioButton)
                                    .addComponent(rightRadioButton))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alphaRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(topRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leftRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (Main.mainProject.getMaskPath().equals("")) {
            JOptionPane.showMessageDialog(Main.interfaceFrame, "Set mask path first", "Alert", JOptionPane.WARNING_MESSAGE);
            Main.interfaceFrame.setMasksAction();
        }

        Mask mask = new Mask();

        String dir = null;
        if (alphaRadioButton.isSelected()) {
            dir = Main.mainProject.getMaskPath() + "/masks-" + MaskType.SELECTIVE_ALPHA.value();
            mask.setType(MaskType.SELECTIVE_ALPHA);
        }

        String filename = nameTextField.getText() + "--";

        if (topRadioButton.isSelected()) {
            filename += VerticalAlign.TOP.value();
            mask.setVerticalAlign(VerticalAlign.TOP);
        } else if (bottomRadioButton.isSelected()) {
            filename += VerticalAlign.BOTTOM.value();
            mask.setVerticalAlign(VerticalAlign.BOTTOM);
        }
        filename += "-";

        if (leftRadioButton.isSelected()) {
            filename += HorizontalAlign.LEFT.value();
            mask.setHorizontalAlign(HorizontalAlign.LEFT);
        } else if (rightRadioButton.isSelected()) {
            filename += HorizontalAlign.RIGHT.value();
            mask.setHorizontalAlign(HorizontalAlign.RIGHT);
        }

        mask.setId(filename);

        filename += ".png";

        mask.setSource("masks-" + mask.getType().value() + "/" + filename);


        File dirFile = new File(dir);
        if (!dirFile.exists());
        dirFile.mkdirs();

        MaskConverter converter = new MaskToImageConverter(node);
        converter.save(new File(dir + "/" + filename));
        Main.mainProject.getSuiteDescriptor().getGlobalConfiguration().getMasks().add(mask);
        Main.interfaceFrame.getProjectFrame().createMaskList();

    }//GEN-LAST:event_saveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alphaRadioButton;
    private javax.swing.JRadioButton bottomRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton leftRadioButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton rightRadioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton topRadioButton;
    // End of variables declaration//GEN-END:variables
}
