/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jboss.rusheye.manager.gui.frames;

import java.awt.Dimension;
import java.awt.Graphics;
import org.jboss.rusheye.manager.Main;
import org.jboss.rusheye.manager.gui.charts.StatisticsPanel;
import org.jboss.rusheye.manager.project.Project;
import org.jboss.rusheye.manager.project.observable.Observed;
import org.jboss.rusheye.manager.project.observable.Observer;

/**
 *
 * @author hcube
 */
public class StatisticsFrame extends javax.swing.JFrame implements Observer {

    private StatisticsPanel statisticsPanel;
    /**
     * Creates new form StatFrame
     */
    public StatisticsFrame() {
        statisticsPanel = new StatisticsPanel();
        setSize(new Dimension(600,470));
        setResizable(false);
    }

    @Override
    public void update(Observed o) {
        System.out.println("Notified");
        if (o instanceof Project)
            statisticsPanel.update(((Project) o).getStatistics());
        this.repaint();
        this.validate();
        
    }
    
    public void update() {
        System.out.println("Notified2");
        statisticsPanel.update(Main.mainProject.getStatistics());
        this.repaint();
        this.validate();
        
    }
    
    public void paint(Graphics g){
        g.drawImage(statisticsPanel.getImage(), 0, 20, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setResizable(false);

        pack();
    }// </editor-fold>
    // Variables declaration - do not modify
    // End of variables declaration
}
