/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jboss.rusheye.manager.gui;

import javax.swing.JPanel;
import org.jboss.rusheye.manager.Main;
import org.jboss.rusheye.manager.gui.view.DoubleView;
import org.jboss.rusheye.manager.gui.view.SingleView;

/**
 *
 * @author hcube
 */
public class SingleViewMenuFrame extends javax.swing.JFrame {

    public static final int PATTERN = 0;
    public static final int SAMPLE = 1;
    public static final int DIFF = 2;
    
    private int state = 2;
    
    private SingleView view;
    /**
     * Creates new form SingleViewMenuFrame
     */
    public SingleViewMenuFrame() {
        initComponents();
    }
    
        public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        patternRadio = new javax.swing.JRadioButton();
        sampleRadio = new javax.swing.JRadioButton();
        diffRadio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        buttonGroup2.add(patternRadio);
        patternRadio.setText("Pattern");
        patternRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patternRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(sampleRadio);
        sampleRadio.setText("Sample");
        sampleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(diffRadio);
        diffRadio.setSelected(true);
        diffRadio.setText("Diff");
        diffRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffRadioActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Mask");
        jCheckBox1.setEnabled(false);

        jButton1.setText("Focus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patternRadio)
                            .addComponent(sampleRadio)
                            .addComponent(diffRadio)
                            .addComponent(jCheckBox1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patternRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diffRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diffRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffRadioActionPerformed
        if (diffRadio.isSelected()) {
            state = SingleViewMenuFrame.DIFF;
            Main.projectFrame.putTestIntoView();
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_diffRadioActionPerformed

    private void sampleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleRadioActionPerformed
        if (sampleRadio.isSelected()) {
            state = SingleViewMenuFrame.SAMPLE;
            Main.projectFrame.putTestIntoView();
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_sampleRadioActionPerformed

    private void patternRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patternRadioActionPerformed
        if (patternRadio.isSelected()) {
            state = SingleViewMenuFrame.PATTERN;
            Main.projectFrame.putTestIntoView();
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_patternRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        view.focus();
        System.out.println("Focused on error");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton diffRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton patternRadio;
    private javax.swing.JRadioButton sampleRadio;
    // End of variables declaration//GEN-END:variables

    public SingleView getView() {
        return view;
    }

    public void setView(SingleView view) {
        this.view = view;
    }

}
