/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jboss.rusheye.gui;

import javax.swing.JPanel;
import org.jboss.rusheye.Main;
import org.jboss.rusheye.gui.view.DoubleView;

/**
 *
 * @author hcube
 */
public class SingleViewMenuFrame extends javax.swing.JFrame {

    public static final int PATTERN = 0;
    public static final int SAMPLE = 1;
    public static final int DIFF = 2;
    
    private int state = 2;
    /**
     * Creates new form SingleViewMenuFrame
     */
    public SingleViewMenuFrame() {
        initComponents();
    }
    
        public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        patternRadio = new javax.swing.JRadioButton();
        sampleRadio = new javax.swing.JRadioButton();
        diffRadio = new javax.swing.JRadioButton();

        buttonGroup2.add(patternRadio);
        patternRadio.setText("Pattern");
        patternRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patternRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(sampleRadio);
        sampleRadio.setText("Sample");
        sampleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(diffRadio);
        diffRadio.setSelected(true);
        diffRadio.setText("Diff");
        diffRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patternRadio)
                    .addComponent(sampleRadio)
                    .addComponent(diffRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patternRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diffRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diffRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffRadioActionPerformed
        if (diffRadio.isSelected()) {
            state = SingleViewMenuFrame.DIFF;
            Main.projectFrame.putTestIntoView();
        }
    }//GEN-LAST:event_diffRadioActionPerformed

    private void sampleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleRadioActionPerformed
        if (sampleRadio.isSelected()) {
            state = SingleViewMenuFrame.SAMPLE;
            Main.projectFrame.putTestIntoView();
        }
    }//GEN-LAST:event_sampleRadioActionPerformed

    private void patternRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patternRadioActionPerformed
        if (patternRadio.isSelected()) {
            state = SingleViewMenuFrame.PATTERN;
            Main.projectFrame.putTestIntoView();
        }
    }//GEN-LAST:event_patternRadioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton diffRadio;
    private javax.swing.JRadioButton patternRadio;
    private javax.swing.JRadioButton sampleRadio;
    // End of variables declaration//GEN-END:variables


}
